# ⠀ⓥ 2024     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignorePatterns:
  - dist/

ignores:
  - '~'
  - '@voltiso/config.ts'
  - '@voltiso/config.tsdoc'
  - '@voltiso/config.jest'
  - '@voltiso/script'
