# ⠀ⓥ 2022     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignorePatterns:
  - dist/

ignores:
  - '~'
  - '@voltiso/config.ts.build.esm'
  - '@voltiso/config.ts.build.cjs'
  - '@voltiso/config.tsdoc'
  - '@voltiso/config.jest'
