# ⠀ⓥ 2025     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '@~/workspace'
  - _
  - '~'
  - '@voltiso/config.ts'
  - '@voltiso/config.jest'
  - '@voltiso/config.tsdoc'
  - '@voltiso/transform'
  - '@voltiso/script'
