# ⠀ⓥ 2022     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '@voltiso/config.ts'
  - '@voltiso/transform'
  - '@voltiso/assertor.transform'
  - typescript-transform-paths
  - typescript
