# ⠀ⓥ 2026     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - "@arethetypeswrong/cli"
  - "@biomejs/biome"
  - "@types/node"
  - "@typescript/analyze-trace" # for TS trace
  - "@voltiso/config.jest"
  - "@voltiso/config.jest.lib"
  - "@voltiso/config.ts"
  - "@voltiso/config.tsdoc"
  - depcheck
  - gnomon # for TS trace
  - jest
  - rimraf
  - ts-node
  - ts-patch
  - tsx # for running tests etc.
  - ttypescript
  - type-coverage
  - typescript
  - typescript-transform-paths
  - zone.js
  - cross-env
