# ⠀ⓥ 2024     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '@types/jest'
  - '@types/node'
  - '@voltiso/config.eslint.lib'
  - '@voltiso/config.jest'
  - '@voltiso/config.jest.lib'
  - '@voltiso/config.prettier'
  - '@voltiso/config.ts'
  - eslint-import-resolver-typescript
  - jest
  - rimraf
  - ts-node
  - ttypescript
  - type-coverage
  - typescript
  - typescript-transform-paths
  - zone.js
