yarnPath: .yarn/releases/yarn-3.1.1.cjs
# packageExtensions:
#   eslint-module-utils@*:
#     dependencies:
#       eslint-import-resolver-node: '*'
# pnpMode: loose
# packageExtensions:
#   'debug@*':
#     peerDependenciesMeta:
#       'supports-color':
#         optional: true
