# ⠀ⓥ 2026     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

packages:
  - libs/*
  - libs/cpp/*

nodeLinker: isolated
autoInstallPeers: false
hoist: false

# dedupePeerDependents: true # default
resolvePeersFromWorkspaceRoot: false # ! make true?

strictPeerDependencies: false
ignoreWorkspaceRootCheck: true
