# ⠀ⓥ 2022     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '~'
  - '@voltiso/config.jest.lib'
  - '@voltiso/config.jest.esr'
  - '@voltiso/util.esbuild'
  - '@firebase/app-types'
  - firebase-tools
