# ⠀ⓥ 2024     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '@~/workspace'
  - '~'
  - '@voltiso/config.jest.lib'
  - '@voltiso/config.jest'
  - '@voltiso/util.esbuild'
  - '@voltiso/script'
  - '@firebase/app-types'
  - firebase-tools
