# ⠀ⓥ 2024     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '@~/workspace'
  - 'prettier-plugin-*'
  - '*/prettier-plugin-*'
  - '@prettier/plugin-*'
  - '@toml-tools/lexer'
  - '@types/node'
  - '@voltiso/config.ts'
  - '@voltiso/config.jest'
  - '@voltiso/script'
