# ⠀ⓥ 2022     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '~'
  - react-native
  - '@babel/core'
  - '@babel/preset-env'
  - '@voltiso/config.jest.esr'
  - '@voltiso/config.ts'
  - '@voltiso/config.ts.build.cjs'
  - '@voltiso/config.ts.build.esm'
