# ⠀ⓥ 2023     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '~'
  - '@voltiso/config.jest'
  - '@voltiso/config.jest.lib'
  - '@voltiso/config.ts.build.esm'
  - '@voltiso/config.ts.build.cjs'
