# ⠀ⓥ 2023     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '@firebase/app-types'
  - '@voltiso/config.jest'
  - '@voltiso/config.ts.build.cjs'
  - '@voltiso/config.ts.build.esm'
