# ⠀ⓥ 2024     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '@~/workspace'
  - '@firebase/app-types'
  - '@voltiso/config.ts'
  - '@voltiso/config.jest'
  - '@voltiso/script'
