# ⠀ⓥ 2023     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - react-native
  - '@babel/core'
  - '@babel/preset-env'
  - '@babel/plugin-transform-react-jsx'
  - '@babel/plugin-proposal-decorators'
  - '@voltiso/config.eslint'
  - '@voltiso/config.jest.react'
  - '@voltiso/config.jest.lib'
  - '@voltiso/config.ts.build.cjs'
  - '@voltiso/config.ts.build.esm'
