import { execSync } from 'node:child_process'
import { readdirSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { llvmCov, llvmProfdata } from './config'

export interface CoverageOptions {
	cwd: string
	testExecutable: string
	thresholdPercent?: number
}

export function testCoverage({
	cwd,
	testExecutable,
	thresholdPercent = 100.0,
}: CoverageOptions) {
	try {
		// 0. Find all .profraw files generated by the test runner
		const profrawFiles = readdirSync(cwd).filter(file =>
			file.endsWith('.profraw'),
		)

		if (profrawFiles.length === 0) {
			console.error(`\n❌ ERROR: No .profraw files found in ${cwd}!`)
			process.exitCode = 1
			return // Exit gracefully to trigger finally block
		}

		console.log(
			`\n🧩 Merging ${profrawFiles.length} LLVM profile data file(s) in ${cwd}...`,
		)

		// 1. Merge all raw profiling data files into the indexed format
		execSync(
			`${llvmProfdata} merge -sparse ${profrawFiles.join(' ')} -o default.profdata`,
			{ stdio: 'inherit', cwd },
		)

		console.log(`📊 Exporting coverage to LCOV...`)
		// Export the coverage data in lcov format e.g. for vscode extension
		const lcovCmd = `${llvmCov} export ${testExecutable} -instr-profile=default.profdata -format=lcov > lcov.info`
		execSync(lcovCmd, {
			cwd,
			encoding: 'utf-8',
			maxBuffer: 1024 * 1024 * 50, // 50MB buffer just in case
		})

		console.log(`📊 Exporting coverage to JSON...`)
		// 2. Export the coverage data to JSON format and capture the stdout in memory
		const exportCmd = `${llvmCov} export ${testExecutable} -instr-profile=default.profdata`
		const jsonOutput = execSync(exportCmd, {
			cwd,
			encoding: 'utf-8',
			maxBuffer: 1024 * 1024 * 50, // 50MB buffer just in case
		})

		// Generate an HTML coverage report
		console.log(`📊 Exporting HTML coverage report...`)
		const htmlCmd = `${llvmCov} show ${testExecutable} -instr-profile=default.profdata -format=html -output-dir=coverage-report`
		execSync(htmlCmd, {
			cwd,
			encoding: 'utf-8',
			maxBuffer: 1024 * 1024 * 50,
		})

		// 3. Parse the JSON and extract the totals
		const coverageData = JSON.parse(jsonOutput)
		const linesPercent = coverageData.data[0].totals.lines.percent

		console.log(`\n========================================`)
		console.log(`📈 Test Coverage: ${linesPercent.toFixed(2)}%`)
		console.log(`========================================`)

		if (linesPercent < thresholdPercent) {
			console.error(
				`\n❌ ERROR: Coverage dropped below ${thresholdPercent}%. Write more tests!`,
			)
			process.exitCode = 1
			return
		}

		console.log(`\n✅ SUCCESS: Coverage is perfect.`)
	} catch (error) {
		console.error(`\n❌ Pipeline failed during coverage extraction.`)
		console.error(error)
		process.exitCode = 1
	} finally {
		rmSync(join(cwd, 'default.profdata'), { force: true })
		readdirSync(cwd)
			.filter(file => file.endsWith('.profraw'))
			.forEach(file => {
				rmSync(join(cwd, file), { force: true })
			})
	}
}
