// ⠀ⓥ 2022     🌩    🌩     ⠀   ⠀
// ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

export type { CustomArray } from '../s/array'
export type { CustomBigint } from '../s/bigint'
export type { CustomBoolean } from '../s/boolean'
export type { CustomFunction } from '../s/function'
export type { CustomInstance } from '../s/instance'
export type { CustomLiteral, CustomUnknownLiteral } from '../s/literal'
export type { CustomNever } from '../s/never'
export type { CustomNumber } from '../s/number'
export type { CustomObject, CustomUnknownObject } from '../s/object'
export type { CustomString } from '../s/string'
export type { CustomSymbol } from '../s/symbol'
export type { CustomTuple, CustomUnknownTuple } from '../s/tuple'
export type { CustomUnion } from '../s/union'
export type { CustomUnknown } from '../s/unknown'
export type { CustomUnknownSchema } from '../s/unknownSchema'
export type { MergeOptions } from '../schema'
export type { CustomSchema } from '../schema'
