# РађРЊЦ 2023     ­ЪїЕ    ­ЪїЕ     Рађ   Рађ
# Рађ         ­ЪїЕ V═Џo═Џ═Џ═Џlt═Џ═Џ═Џi═Џ═Џ═Џ═Џso═Џ═Џ═Џ.comРађ  РађРађРађ

# РађРЊЦ 2023     ­ЪїЕ    ­ЪїЕ     Рађ   Рађ
# Рађ         ­ЪїЕ V═Џo═Џ═Џ═Џlt═Џ═Џ═Џi═Џ═Џ═Џ═Џso═Џ═Џ═Џ.comРађ  РађРађРађ

ignores:
  - _
  - '~'
  - '@voltiso/config.tsdoc'
  - '@voltiso/config.jest'
