# ⠀ⓥ 2022     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '@babel/core'
  - '@babel/plugin-proposal-decorators'
  - '@voltiso/config.jest.react'
  - '@voltiso/config.ts.build.cjs'
  - '@voltiso/config.ts.build.esm'
