# ⠀ⓥ 2026     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '~'
  - '@voltiso/script'
  - '@babel/core'
  - '@babel/preset-env'
  - '@babel/plugin-transform-react-jsx'
  - '@babel/plugin-proposal-decorators'
