# ⠀ⓥ 2022     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignorePatterns:
  - dist/

ignores:
  - assert
  - '@voltiso/assertor.transform'
  - '@voltiso/config.ts.build.esm'
  - '@voltiso/config.ts.build.cjs'
  - '@types/assert'
