# ⠀ⓥ 2022     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - assert
  - '@types/assert'
  - '@voltiso/config.ts'
  - '@voltiso/config.ts.build.cjs'
  - '@voltiso/config.ts.build.esm'
