# ⠀ⓥ 2023     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '~'
  - '@babel/core'
  - '@babel/preset-env'
  - '@babel/plugin-transform-react-jsx'
  - '@voltiso/config.ts.build.cjs'
  - '@voltiso/config.ts.build.esm'
  - '@voltiso/config.eslint.lib'
  - '@voltiso/config.jest.react'
  - '@jest/types'
  - '@types/react-test-renderer'
  - '@types/testing-library__jest-dom' # extend-expect
