# ⠀ⓥ 2025     🌩    🌩     ⠀   ⠀
# ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

ignores:
  - '@~/workspace'
  - '~'
  - react-native
  - '@babel/core'
  - '@babel/preset-env'
  - '@voltiso/config.ts'
  - '@voltiso/config.jest.react'
  - '@voltiso/script'
