// ⠀ⓥ 2022     🌩    🌩     ⠀   ⠀
// ⠀         🌩 V͛o͛͛͛lt͛͛͛i͛͛͛͛so͛͛͛.com⠀  ⠀⠀⠀

import * as fs from 'node:fs/promises'
import * as path from 'node:path'

export async function writeFirebaseJson(params: { port: number; cwd: string }) {
	const firebaseJson = {
		emulators: {
			ui: {
				enabled: false,
			},

			firestore: {
				port: params.port,
			},
		},
	}

	// eslint-disable-next-line security/detect-non-literal-fs-filename
	await fs.writeFile(
		path.join(params.cwd, 'firebase.json'),
		`// AUTO-GENERATED by script/jest-with-firestore-emu\n${JSON.stringify(
			firebaseJson,
		)}`,
	)
}
